version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://spidey:spidey123@db:5432/spidey_feedback
      - SECRET_KEY=your-super-secret-key-here
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USE_TLS=${SMTP_USE_TLS:-True}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-spideyofficial777@gmail.com}
      - ADMIN_DEFAULT_PASSWORD=${ADMIN_DEFAULT_PASSWORD:-Admin@1234}
      - APP_NAME=Spidey Feedback
      - APP_URL=http://localhost:5000
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=spidey_feedback
      - POSTGRES_USER=spidey
      - POSTGRES_PASSWORD=spidey123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: